import {Component, ViewChild} from '@angular/core';
import {NavController, NavParams, Content} from 'ionic-angular';
import {ItemDetailsPage} from '../item-details/item-details';

@Component({
  templateUrl: 'build/pages/list/list.html',
})

export class ListPage {
  selectedId: any;
  public flag;
  
  subMenus: Array<{id: number, border_type:number, title: string, contain: string, parent_id: number, type: string, child_type: number, url: string}>;
  @ViewChild(Content) content: Content;
  constructor(private navCtrl: NavController, navParams: NavParams) {
    
    this.selectedId = navParams.get('menuId'); 

    this.flag = "0";
    this.subMenus = [
      { id: 5,   border_type: 1, title: '8 day challenge',                            contain: 'none',  parent_id: 1,  type: 'list', child_type: 1, url: ''},
      { id: 6,   border_type: 2, title: '8 day micro course',                         contain: 'none',  parent_id: 1,  type: 'list', child_type: 2, url: ''},
      { id: 7,   border_type: 3, title: 'More',                                       contain: 'none',  parent_id: 1,  type: 'list', child_type: 3, url: ''},
      { id: 8,   border_type: 1, title: "I like them short",                          contain: 'none',  parent_id: 2,  type: 'list', child_type: 1, url: ''},
      { id: 9,   border_type: 2, title: "I'm used to this",                           contain: 'none',  parent_id: 2,  type: 'list', child_type: 1, url: ''},
      { id: 10,  border_type: 3, title: "Let's go deeper",                            contain: 'none',  parent_id: 2,  type: 'list', child_type: 3, url: ''},
      { id: 11,  border_type: 1, title: 'AN IMAGINARY LINE',                          contain: 'video', parent_id: 3,  type: 'html', child_type: 1, url: 'assets/experience/201-How-to-meditate.html'},
      { id: 12,  border_type: 2, title: 'AN IMAGINARY BALLOON',                       contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 13,  border_type: 3, title: 'CHOOSE IT - USE IT',                         contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 14,  border_type: 1, title: 'GETTING WITH THE FLOW',                      contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 15,  border_type: 2, title: 'AWARENESS TRAINING WITH A BELL',             contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 16,  border_type: 3, title: 'THE WORLD OUTSIDE',                          contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 17,  border_type: 1, title: 'BEING IN THE BODY',                          contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 18,  border_type: 2, title: 'MINDFUL CHECK IN',                           contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 19,  border_type: 3, title: 'CHOOSE IT - USE IT (EXTENDED - 22 MINS)',    contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 20,  border_type: 1, title: 'THE BREATH AND BEYOND',                      contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 21,  border_type: 2, title: 'BODY-MIND-WORLD',                            contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 22,  border_type: 3, title: 'OUT AND ABOUT',                              contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 23,  border_type: 1, title: 'WITH THE WORLD',                             contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 24,  border_type: 2, title: 'LETING GO OF CONTROL',                       contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 25,  border_type: 3, title: 'THE BODY AND BEYOND',                        contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 26,  border_type: 1, title: 'THE FOUR PHASE PRACTICE',                    contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 27,  border_type: 2, title: 'NOTHING MATTERS',                            contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 28,  border_type: 3, title: 'RELEASING RESISTANCE',                       contain: 'video', parent_id: 3,  type: 'html', child_type: 2, url: 'assets/more/505.Getting-to-the-heart-of-it.html'},
      { id: 29,  border_type: 1, title: 'Intro to the book',                          contain: 'none',  parent_id: 4,  type: 'menu', child_type: 1, url: ''},
      { id: 30,  border_type: 2, title: 'Introduction to mindfulness',                contain: 'none',  parent_id: 4,  type: 'menu', child_type: 3, url: ''},
      { id: 31,  border_type: 3, title: 'Mind and emotions',                          contain: 'none',  parent_id: 4,  type: 'menu', child_type: 3, url: ''},
      { id: 32,  border_type: 1, title: 'Patterns of behaviour',                      contain: 'none',  parent_id: 4,  type: 'menu', child_type: 3, url: ''},
      { id: 33,  border_type: 2, title: 'The art of allowing',                        contain: 'none',  parent_id: 4,  type: 'menu', child_type: 3, url: ''},
      { id: 34,  border_type: 3, title: 'Final words',                                contain: 'none',  parent_id: 4,  type: 'menu', child_type: 3, url: ''},
      { id: 35,  border_type: 1, title: 'Guided Mindfulness',                         contain: 'none',  parent_id: 8,  type: 'list', child_type: 1, url: ''},
      { id: 36,  border_type: 2, title: 'Experientail Exercises',                     contain: 'none',  parent_id: 8,  type: 'list', child_type: 2, url: ''},
      { id: 37,  border_type: 3, title: 'Tips And Tools',                             contain: 'none',  parent_id: 8,  type: 'list', child_type: 3, url: ''},
      { id: 38,  border_type: 1, title: 'Guided Meditations',                         contain: 'none',  parent_id: 9,  type: 'list', child_type: 1, url: 'assets/knowledge/1.Intro-to-the-book/300.Introduction-to-this-book.html'},
      { id: 39,  border_type: 2, title: 'Experientail Exercises',                     contain: 'none',  parent_id: 9,  type: 'list', child_type: 2, url: 'assets/experience/202.Mindful-Check-In-9mins.html'},
      { id: 40,  border_type: 3, title: 'Tips And Tools',                             contain: 'none',  parent_id: 9,  type: 'list', child_type: 3, url: 'assets/more/501.Getting-to-the-heart-of-it-video.html'},
      { id: 41,  border_type: 1, title: 'Mindfulness Meditations',                    contain: 'none',  parent_id: 10, type: 'list', child_type: 1, url: 'assets/knowledge/1.Intro-to-the-book/300.Introduction-to-this-book.html'},
      { id: 42,  border_type: 2, title: 'Experientail Exercises',                     contain: 'none',  parent_id: 10, type: 'list', child_type: 2, url: 'assets/experience/202.Mindful-Check-In-9mins.html'},
      { id: 43,  border_type: 3, title: 'Tips And Tools',                             contain: 'none',  parent_id: 10, type: 'list', child_type: 3, url: 'assets/more/501.Getting-to-the-heart-of-it-video.html'},
      { id: 44,  border_type: 1, title: 'Sub Heads',                                  contain: 'none',  parent_id: 13, type: 'html', child_type: 3, url: 'assets/knowledge/3.Mind-and-emotions/3.Feelings-as-feelings/325.Normal-human-emotions.html'},
      { id: 45,  border_type: 2, title: 'Sub Heads',                                  contain: 'none',  parent_id: 14, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 46,  border_type: 1, title: 'Mindfulness is like a triangle',             contain: 'none',  parent_id: 15, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 47,  border_type: 2, title: 'An imaginary balloon (7 mins)',              contain: 'none',  parent_id: 15, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 48,  border_type: 3, title: 'An imaginary line (8 mins)',                 contain: 'none',  parent_id: 15, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 49,  border_type: 1, title: 'Choose it - Use it (8 mins)',                contain: 'none',  parent_id: 15, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 50,  border_type: 2, title: 'Getting with the flow (7 mins)',             contain: 'none',  parent_id: 15, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 51,  border_type: 3, title: 'The world outside (11 mins)',                contain: 'none',  parent_id: 15, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 52,  border_type: 1, title: 'Being in the body (11 mins)',                contain: 'none',  parent_id: 15, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 53,  border_type: 1, title: 'Stories on a Stream',                        contain: 'none',  parent_id: 16, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 54,  border_type: 2, title: 'Three minute nothing exercise',              contain: 'none',  parent_id: 16, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 55,  border_type: 3, title: 'Be here now',                                contain: 'none',  parent_id: 16, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 56,  border_type: 1, title: 'One minute BMW',                             contain: 'none',  parent_id: 17, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 57,  border_type: 2, title: 'Stepping back',                              contain: 'none',  parent_id: 17, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 58,  border_type: 3, title: 'Labelling',                                  contain: 'none',  parent_id: 17, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 59,  border_type: 1, title: 'SOS 1',                                      contain: 'none',  parent_id: 17, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 60,  border_type: 1, title: 'THOUGHTS ARE LIKE RAIN ON A WINDSCREEN',     contain: 'none',  parent_id: 18, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 61,  border_type: 2, title: 'MINDFUL CHECK-IN',                           contain: 'none',  parent_id: 18, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 62,  border_type: 3, title: 'CHOOSE IT - USE IT',                         contain: 'none',  parent_id: 18, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 63,  border_type: 1, title: 'THE BREATH AND BEYOND',                      contain: 'none',  parent_id: 18, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 64,  border_type: 2, title: 'BODY-MIND-WORLD',                            contain: 'none',  parent_id: 18, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 65,  border_type: 3, title: 'OUT AND ABOUT',                              contain: 'none',  parent_id: 18, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 66,  border_type: 1, title: 'WITH THE WORLD',                             contain: 'none',  parent_id: 18, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 67,  border_type: 2, title: 'LETTING GO OF CONTROL',                      contain: 'none',  parent_id: 18, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 68,  border_type: 3, title: 'BALLOONS IN THE SKY',                        contain: 'none',  parent_id: 19, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 69,  border_type: 1, title: 'THOUGHTS AS THINGS',                         contain: 'none',  parent_id: 19, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 70,  border_type: 2, title: 'THE OBSERVER WITHIN',                        contain: 'none',  parent_id: 19, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 71,  border_type: 3, title: 'THE ART OF ALLWOING',                        contain: 'none',  parent_id: 19, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 72,  border_type: 1, title: 'TWO MINUTE STRESS RELEASE',                  contain: 'none',  parent_id: 20, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 73,  border_type: 2, title: 'THREE MINUTE BMW',                           contain: 'none',  parent_id: 20, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 74,  border_type: 3, title: 'ANCHORING',                                  contain: 'none',  parent_id: 20, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 75,  border_type: 1, title: 'SOS 2',                                      contain: 'none',  parent_id: 20, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 76,  border_type: 1, title: 'FEELINGS ARE LIKE PEOPLE AT A GUESTHOUSE',   contain: 'none',  parent_id: 21, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 77,  border_type: 2, title: 'THE BODY AND BEYOND',                        contain: 'none',  parent_id: 21, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 78,  border_type: 3, title: 'THE FOUR PHASE PRACTICE',                    contain: 'none',  parent_id: 21, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 79,  border_type: 1, title: 'NOTHING MATTERS',                            contain: 'none',  parent_id: 21, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 90,  border_type: 2, title: 'CHOOSE IT - USE IT',                         contain: 'none',  parent_id: 21, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 91,  border_type: 3, title: 'UNGUIDED',                                   contain: 'none',  parent_id: 21, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 92,  border_type: 1, title: 'RELEASING RESISTANCE',                       contain: 'none',  parent_id: 21, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 93,  border_type: 2, title: 'THOUGHT SCREEN',                             contain: 'none',  parent_id: 22, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 94,  border_type: 3, title: 'THE OBSERVER WITHIN',                        contain: 'none',  parent_id: 22, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 95,  border_type: 1, title: 'THE ART OF ALLWOING',                        contain: 'none',  parent_id: 22, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 96,  border_type: 2, title: 'BE HERE NOW',                                contain: 'none',  parent_id: 22, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 97,  border_type: 1, title: 'THREE MINUTE BREATHING SPACE',               contain: 'none',  parent_id: 23, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 98,  border_type: 2, title: 'REMEMBER WHO YOU ARE',                       contain: 'none',  parent_id: 23, type: 'html', child_type: 2, url: 'assets/welcome/100.Introduction.html'},
      { id: 99,  border_type: 3, title: 'SOS 3',                                      contain: 'none',  parent_id: 23, type: 'html', child_type: 3, url: 'assets/welcome/100.Introduction.html'},
      { id: 100, border_type: 1, title: 'The 8 Day Challenge',                        contain: 'none',  parent_id: 5,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 101, border_type: 2, title: 'Introduction',                               contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 102, border_type: 3, title: 'Mindfulness is...',                          contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 103, border_type: 1, title: 'Meaningful connection',                      contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 104, border_type: 2, title: 'Thoughts and thinking',                      contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 105, border_type: 3, title: 'Emotions and feeling',                       contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 106, border_type: 1, title: 'Patterns of behaviour',                      contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 107, border_type: 2, title: 'Resistance traps',                           contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 108, border_type: 3, title: 'The observer',                               contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 109, border_type: 1, title: 'Turning towards',                            contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 110, border_type: 2, title: 'End of course',                              contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 111, border_type: 3, title: 'And after this',                             contain: 'none',  parent_id: 6,  type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 112, border_type: 1, title: 'Introduction to this book',                  contain: 'none',  parent_id: 29, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 113, border_type: 2, title: 'Start',                                      contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 114, border_type: 3, title: 'What is mindfulness - part one',             contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 115, border_type: 1, title: 'What is mindfulness - part two',             contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 116, border_type: 2, title: 'Meaningful connection - part one',           contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 117, border_type: 3, title: 'Meaningful connection - part two',           contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 118, border_type: 1, title: 'Meaningful connection - part three',         contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 119, border_type: 2, title: 'Overcoming boredom - part two',              contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 120, border_type: 3, title: 'Overcoming boredom - part one',              contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 121, border_type: 1, title: 'Distractions',                               contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 122, border_type: 2, title: 'Being content with a monkey mind',           contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 123, border_type: 3, title: 'A new dimension to things',                  contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 124, border_type: 1, title: 'End of section',                             contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 125, border_type: 2, title: 'Summary',                                    contain: 'none',  parent_id: 30, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 126, border_type: 1, title: 'Your Mind',                                  contain: 'none',  parent_id: 31, type: 'list', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 127, border_type: 2, title: 'Thoughts as thoughts',                       contain: 'none',  parent_id: 31, type: 'list', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 128, border_type: 3, title: 'Feelings as feelings',                       contain: 'none',  parent_id: 31, type: 'list', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 129, border_type: 1, title: 'Start',                                      contain: 'none',  parent_id: 126,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 130, border_type: 2, title: 'What is my mind',                            contain: 'none',  parent_id: 126,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 131, border_type: 3, title: 'Input only',                                 contain: 'none',  parent_id: 126,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 132, border_type: 1, title: 'Thought upon thought',                       contain: 'none',  parent_id: 126,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 133, border_type: 2, title: 'Internal and external world problems',       contain: 'none',  parent_id: 126,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 134, border_type: 3, title: 'A problem with problem-solving',             contain: 'none',  parent_id: 126,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 135, border_type: 1, title: 'End of section',                             contain: 'none',  parent_id: 126,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 136, border_type: 2, title: 'Summary',                                    contain: 'none',  parent_id: 126,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 137, border_type: 1, title: 'Start',                                      contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 138, border_type: 2, title: 'Associations - part one 2',                  contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 139, border_type: 3, title: 'Associations - part one',                    contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 140, border_type: 1, title: 'Associations - part two',                    contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 141, border_type: 2, title: 'Solutions',                                  contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 142, border_type: 3, title: 'Buying and battling',                        contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 143, border_type: 1, title: 'Not feeling better',                         contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 144, border_type: 2, title: 'Sounds on the outside',                      contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 145, border_type: 3, title: 'End of section',                             contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 146, border_type: 1, title: 'Summary',                                    contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 147, border_type: 1, title: 'Start',                                      contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 148, border_type: 2, title: 'Fear',                                       contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 149, border_type: 3, title: 'Normal human emotions',                      contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 150, border_type: 1, title: 'Good or bad',                                contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 151, border_type: 2, title: 'A beautiful but uncomfortable sunrise',      contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 152, border_type: 3, title: 'End of section',                             contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 153, border_type: 1, title: 'Summary',                                    contain: 'none',  parent_id: 127,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 154, border_type: 1, title: 'The little patterns',                        contain: 'none',  parent_id: 32, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 155, border_type: 2, title: 'Inner resistance',                           contain: 'none',  parent_id: 32, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 156, border_type: 3, title: 'Resistance traps',                           contain: 'none',  parent_id: 32, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 157, border_type: 1, title: 'Start',                                      contain: 'none',  parent_id: 154,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 158, border_type: 1, title: 'The little patterns - part one',             contain: 'none',  parent_id: 154,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 159, border_type: 3, title: 'The little patterns - part two',             contain: 'none',  parent_id: 154,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 160, border_type: 1, title: 'More and more',                              contain: 'none',  parent_id: 154,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 161, border_type: 2, title: 'End of section',                             contain: 'none',  parent_id: 154,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 162, border_type: 3, title: 'Summary',                                    contain: 'none',  parent_id: 154,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 163, border_type: 1, title: 'Start',                                      contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 164, border_type: 2, title: 'Inner resistance',                           contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 165, border_type: 3, title: 'What a state',                               contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 166, border_type: 1, title: 'Quick fixes',                                contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 167, border_type: 2, title: 'Do you really want to',                      contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 168, border_type: 3, title: 'Arguing with reality',                       contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 169, border_type: 1, title: 'The feeling good trap - part two',           contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 170, border_type: 2, title: 'The feeling good trap - part three',         contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 171, border_type: 3, title: 'The feeling good trap - part one',           contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 172, border_type: 1, title: 'In (or out of) control',                     contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 173, border_type: 2, title: 'How your brain changes with mindfulness',    contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 174, border_type: 3, title: 'Neuro-what',                                 contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 175, border_type: 1, title: 'End of section',                             contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 176, border_type: 2, title: 'Summary',                                    contain: 'none',  parent_id: 155,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 177, border_type: 1, title: 'Start',                                      contain: 'none',  parent_id: 156,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 178, border_type: 2, title: 'Catherine the chameleon',                    contain: 'none',  parent_id: 156,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 179, border_type: 3, title: 'Sarita the scratcher',                       contain: 'none',  parent_id: 156,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 180, border_type: 1, title: 'Suzie and Soloman',                          contain: 'none',  parent_id: 156,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 181, border_type: 2, title: 'Joe the joker',                              contain: 'none',  parent_id: 156,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 182, border_type: 3, title: 'Reuben the rebel',                           contain: 'none',  parent_id: 156,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 183, border_type: 1, title: 'End of section',                             contain: 'none',  parent_id: 156,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 184, border_type: 2, title: 'Summary',                                    contain: 'none',  parent_id: 156,type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 185, border_type: 1, title: 'Start',                                      contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 186, border_type: 2, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 187, border_type: 3, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 188, border_type: 1, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 189, border_type: 2, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 190, border_type: 3, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 191, border_type: 1, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 192, border_type: 2, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 193, border_type: 3, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
      { id: 194, border_type: 1, title: 'Summary',                                    contain: 'none',  parent_id: 33, type: 'html', child_type: 1, url: 'assets/welcome/100.Introduction.html'},
    ]; 
  }

  sayHello(str) {
    this.selectedId=str;
  };
  
  getValue() {
    return this.selectedId;
  };
  
  scrollTo() {
    this.content.scrollTo(0, 500, 200);
  }

}
